export const FORTUNE_QUOTES = [
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "The only way to do great work is to love what you do.",
  "Innovation distinguishes between a leader and a follower.",
  "Your limitation—it's only your imagination.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn't just find you. You have to go out and get it.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Dream bigger. Do bigger.",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It's going to be hard, but hard does not mean impossible.",
  "Don't wait for opportunity. Create it.",
  "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Believe it. Build it.",
  "The expert in anything was once a beginner.",
  "Every accomplishment starts with the decision to try.",
];

export const WORD_BANK = [
  "REACT",
  "CODE",
  "GAME",
  "WORD",
  "FIND",
  "SWIFT",
  "KOTLIN",
  "RUST",
  "SWIFTUI",
  "PYTHON",
  "JAVA",
  "HTML",
  "CSS",
  "COMPUTER",
  "PROGRAM",
  "DEMO",
  "SOFTWARE",
  "HARDWARE",
  "NETWORK",
  "DATABASE",
  "SERVER",
  "CLIENT",
  "PROD",
  "LIBRARY",
  "FUNCTION",
  "VARIABLE",
  "OBJECT",
  "ARRAY",
  "STRING",
  "NUMBER",
  "BOOLEAN",
  "LOOP",
  "DEV",
  "SWITCH",
  "GENAI",
  "VSCODE",
  "CLASS",
  "METHOD",
  "PROPERTY",
  "EVENT",
  "LISTENER",
  "CALLBACK",
  "PROMISE",
  "ASYNC",
  "AWAIT",
  "FETCH",
  "API",
  "REST",
  "JSON",
  "XML",
  "HTTP",
  "HTTPS",
  "URL",
  "BROWSER",
  "CHROME",
  "FIREFOX",
  "SAFARI",
  "EDGE",
  "MOBILE",
  "TABLET",
  "DESKTOP",
  "FAST",
  "DESIGN",
  "FRONTEND",
  "BACKEND",
  "FULLSTACK",
  "DEVOPS",
  "TESTING",
  "DEBUG",
  "BUILD",
  "DEPLOY",
  "VERSION",
  "GIT",
  "GITHUB",
  "BRANCH",
  "COMMIT",
  "MERGE",
  "PULL",
  "PUSH",
  "CLONE",
  "FORK",
  "ISSUE",
  "REVIEW",
  "AGILE",
  "SCRUM",
  "SPRINT",
  "KANBAN",
  "TEAM",
  "PROJECT",
  "FEATURE",
  "BUG",
  "FIX",
  "PATCH",
  "RELEASE",
  "UPDATE",
  "UPGRADE",
  "MIGRATE",
  "REFACTOR",
  "OPTIMIZE",
  "THREAD",
  "SECURITY",
  "ACCESS",
  "AUTH",
];
